using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Database.Entities
{
    public class User : IdentityUser<Guid>
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // auto-generated by the db
        public int Id { get; set; }
        [MaxLength(30)]
        public string? UserName { get; set; }
        public string? Password { get; set; }
        public DateTime CreatedTimeStamp { get; set; }
    }
}
